import type { DummyUser, Product } from "@/types";

// Mock data for tests - recreated as a simple export file
export const mockUsers = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    username: "johndoe",
    birthDate: "1990-01-01",
    image: "https://example.com/avatar1.jpg",
    bloodGroup: "A+",
    height: 175,
    weight: 70,
    eyeColor: "Brown",
    hair: { color: "Brown", type: "Curly" },
    ip: "192.168.1.1",
    address: {
      address: "123 Main St",
      city: "New York",
      state: "NY",
      stateCode: "NY",
      postalCode: "10001",
      coordinates: { lat: 40.7128, lng: -74.006 },
      country: "United States",
    },
    macAddress: "00:B0:D0:63:C2:26",
    university: "Test University",
    bank: {
      cardExpire: "12/25",
      cardNumber: "1234567890123456",
      cardType: "Visa",
      currency: "USD",
      iban: "US33ABCD1234567890",
    },
    company: {
      department: "Engineering",
      name: "Test Company",
      title: "Software Engineer",
      address: {
        address: "456 Business Ave",
        city: "New York",
        state: "NY",
        stateCode: "NY",
        postalCode: "10002",
        coordinates: { lat: 40.7589, lng: -73.9851 },
        country: "United States",
      },
    },
    ein: "12-3456789",
    ssn: "123456789",
    userAgent: "Mozilla/5.0",
    crypto: {
      coin: "Bitcoin",
      wallet: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
      network: "Ethereum Mainnet",
    },
    role: "user",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    username: "janesmith",
    birthDate: "1985-05-15",
    image: "https://example.com/avatar2.jpg",
    bloodGroup: "B+",
    height: 165,
    weight: 60,
    eyeColor: "Blue",
    hair: { color: "Blonde", type: "Straight" },
    ip: "192.168.1.2",
    address: {
      address: "789 Oak Ave",
      city: "Los Angeles",
      state: "CA",
      stateCode: "CA",
      postalCode: "90210",
      coordinates: { lat: 34.0522, lng: -118.2437 },
      country: "United States",
    },
    macAddress: "00:B0:D0:63:C2:27",
    university: "UCLA",
    bank: {
      cardExpire: "11/26",
      cardNumber: "9876543210987654",
      cardType: "MasterCard",
      currency: "USD",
      iban: "US33WXYZ9876543210",
    },
    company: {
      department: "Marketing",
      name: "Creative Agency",
      title: "Marketing Manager",
      address: {
        address: "321 Creative Blvd",
        city: "Los Angeles",
        state: "CA",
        stateCode: "CA",
        postalCode: "90211",
        coordinates: { lat: 34.0736, lng: -118.4004 },
        country: "United States",
      },
    },
    ein: "98-7654321",
    ssn: "987654321",
    userAgent: "Mozilla/5.0",
    crypto: {
      coin: "Ethereum",
      wallet: "0x742d35Cc6634C0532925a3b8D4C8c05bB3aDc1B7",
      network: "Ethereum Mainnet",
    },
    role: "admin",
  },
] as DummyUser[];

export const mockProducts = [
  {
    id: "1",
    name: "iPhone 15 Pro",
    description: "Latest iPhone with advanced features",
    category: "smartphones",
    price: 999.99,
    stock: 50,
    imageUrl: "https://example.com/iphone15pro-thumb.jpg",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-15T00:00:00.000Z",
    brand: "Apple",
    rating: 4.8,
    discountPercentage: 5,
    thumbnail: "https://example.com/iphone15pro-thumb.jpg",
    images: [
      "https://example.com/iphone15pro-1.jpg",
      "https://example.com/iphone15pro-2.jpg",
    ],
  },
  {
    id: "2",
    name: "MacBook Air M2",
    description: "Lightweight laptop with M2 chip",
    category: "laptops",
    price: 1199.99,
    stock: 25,
    imageUrl: "https://example.com/macbook-air-m2-thumb.jpg",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-10T00:00:00.000Z",
    brand: "Apple",
    rating: 4.7,
    discountPercentage: 8,
    thumbnail: "https://example.com/macbook-air-m2-thumb.jpg",
    images: [
      "https://example.com/macbook-air-m2-1.jpg",
      "https://example.com/macbook-air-m2-2.jpg",
    ],
  },
] as Product[];
